[workspace]
members = [
    "exonum",
    "testkit",
    "testkit/server",
    "services/configuration",
    "services/time",
    "examples/cryptocurrency-advanced/backend",
]
exclude = [ "exonum/fuzz" ]
